title: lizzij log
name: "Eliza's Tech Blog"
author: Eliza Huang
twitter_username: liz_zij
baseurl: "/"
description: Learning. But you gotta do it every day.
profile_url: "http://lizzij.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
